"""empty message

Revision ID: 0f78ae1cc93c
Revises: b0b1800266bd
Create Date: 2025-03-19 23:32:32.071851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f78ae1cc93c'
down_revision = 'b0b1800266bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=False),
    sa.Column('end_date', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('hotel_name', sa.String(length=100), nullable=True),
    sa.Column('hotel_location', sa.String(length=100), nullable=True),
    sa.Column('attraction_name', sa.String(length=100), nullable=True),
    sa.Column('attraction_location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itineraries')
    # ### end Alembic commands ###
