"""empty message

Revision ID: 69c58b2d4a93
Revises: 0f78ae1cc93c
Create Date: 2025-03-19 23:44:56.030160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69c58b2d4a93'
down_revision = '0f78ae1cc93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=False),
    sa.Column('end_date', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('hotel_name', sa.String(length=100), nullable=True),
    sa.Column('hotel_location', sa.String(length=100), nullable=True),
    sa.Column('attraction_name', sa.String(length=100), nullable=True),
    sa.Column('attraction_location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('itineraries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itineraries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hotel_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hotel_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('attraction_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('attraction_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='itineraries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='itineraries_pkey')
    )
    op.drop_table('itinerary')
    # ### end Alembic commands ###
