"""empty message

Revision ID: af8268cb4e97
Revises: 
Create Date: 2025-04-05 00:24:19.927337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8268cb4e97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('avatar', sa.String(length=255), nullable=True))

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.alter_column('photo_reference',
                              existing_type=sa.VARCHAR(length=255),
                              type_=sa.Text(),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.alter_column('photo_reference',
                              existing_type=sa.Text(),
                              type_=sa.VARCHAR(length=255),
                              existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
