"""empty message

Revision ID: b0b1800266bd
Revises: 62ca56ffb6f1
Create Date: 2025-03-19 23:26:23.469099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0b1800266bd'
down_revision = '62ca56ffb6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itineraries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itineraries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hotel_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hotel_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('attraction_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('attraction_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='itineraries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='itineraries_pkey')
    )
    # ### end Alembic commands ###
