"""empty message

Revision ID: d10c5eadb2dd
Revises: 0763d677d453
Create Date: 2025-03-15 17:13:48.869168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10c5eadb2dd'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(), nullable=True),
    sa.Column('hotel_location', sa.String(), nullable=True),
    sa.Column('attraction_name', sa.String(), nullable=True),
    sa.Column('attraction_location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerary')
    # ### end Alembic commands ###
