"""empty message

Revision ID: e2a3bce3b234
Revises: d10c5eadb2dd
Create Date: 2025-03-17 23:42:58.618154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a3bce3b234'
down_revision = 'd10c5eadb2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
